[package]
name = "gulf-platform-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
bitflags = { workspace = true }
gulf-core = { path = "../core/" }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, optional = true }
# tinyvec = { workspace = true }

[features]
default = ["tokio"]

alloc = []
std = ["alloc", "bitflags/std", "gulf-core/std", "libc/std", "log/std"]

tokio = ["dep:tokio", "std"]

[lints]
workspace = true
